BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "zcu208_remote"
BBFILE_PATTERN_zcu208_remote = "^${LAYERDIR}/"
BBFILE_PRIORITY_zcu208_remote = "8"

LAYERSERIES_COMPAT_zcu208_remote = "scarthgap"
