BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rfsoc4x2_remote"
BBFILE_PATTERN_rfsoc4x2_remote = "^${LAYERDIR}/"
BBFILE_PRIORITY_rfsoc4x2_remote = "8"

LAYERSERIES_COMPAT_rfsoc4x2_remote = "scarthgap"
