# Copyright (C) 2022 Xilinx, Inc
# SPDX-License-Identifier: BSD-3-Clause



NO_ADC_TILES = 4
NO_DAC_TILES = 4
NO_ADC_BLOCKS_PTILE = 4
NO_DAC_BLOCKS_PTILE = 4

NO_ADC_BLOCKS = NO_ADC_BLOCKS_PTILE * NO_ADC_TILES
NO_DAC_BLOCKS = NO_DAC_BLOCKS_PTILE * NO_DAC_TILES

