BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "zcu111_remote"
BBFILE_PATTERN_zcu111_remote = "^${LAYERDIR}/"
BBFILE_PRIORITY_zcu111_remote = "8"

LAYERSERIES_COMPAT_zcu111_remote = "scarthgap"
